### ISSUE TITLE
How often to run auto z calibrate vs auto z offset?

### ISSUE THREAD

**Issue by vonwerderc** [frap129/OpenQ1#14]
Just curious on if we need to run the calibration before every print the way the stock firmware does? Is there a recommended timeframe to recalibrate? Based on time, number of prints, etc? 

Once we upgrade, can we update Klipper/Moonraker freely every time a new update is released?

**Comment by frap129** [comment]
No, as long as you save the offset to your config you do not have to recalibrate prior to every print. The only times you need to re calibrate are when you change things that affect the Z distance between the tip of the nozzle and the inductive probe (like replacing the nozzle) or when you significantly change the distance between the metal part of the bed and the actual print surface (like putting tape on the build plate).

You can update any of the firmware components, they all use the official versions without modifications. However, the `qidi_auto_z_offset` plugin may break if klipper modifies how probes are handled, at which point you will have to wait for an update to fix it, or remove it from your config and measure Z offset the klipper way.
