### ISSUE TITLE
mcu_configs folder empty 24.2.0-20240508-2203

### ISSUE THREAD

**Issue by 53Aries** [frap129/OpenQ1#2]
![Screenshot 2024-06-02 200203](https://github.com/frap129/OpenQ1/assets/110708581/54394950-531c-4218-9bac-0467d4e1d134)
cp: cannot stat '/home/mks/openq1/mcu_configs/.config.mainboard': No such file or directory

**Comment by 53Aries** [comment]
Also I cant figure out how to add the files to the klipper/config folder properly. I add them but they dont seem to have any effect on the menuconfig. Trying to decipher the file and select the correct settings manually. Can you just provide a screenshot of the menuconfig settings?

**Comment by Peck07** [comment]
The folder is not empty, windows probably doesn't show the .xxxx files.
cp fails because the path is wrong, instead openq1 try OpenQ1 (linux is case sensitive)

**Comment by frap129** [comment]
> cp: cannot stat '/home/mks/openq1/mcu_configs/.config.mainboard': No such file or directory
Where is this error from?

> Also I cant figure out how to add the files to the klipper/config folder properly. I add them but they dont seem to have any effect on the menuconfig. Trying to decipher the file and select the correct settings manually. Can you just provide a screenshot of the menuconfig settings?

You're missing the `.` in front of config. They do not go in the config folder, the need to be copied to the klipper folder with the name `.config`.

**Comment by 53Aries** [comment]
> > cp: cannot stat '/home/mks/openq1/mcu_configs/.config.mainboard': No such file or directory
> 
> Where is this error from?
> 
> > Also I cant figure out how to add the files to the klipper/config folder properly. I add them but they dont seem to have any effect on the menuconfig. Trying to decipher the file and select the correct settings manually. Can you just provide a screenshot of the menuconfig settings?
> 
> You're missing the `.` in front of config. They do not go in the config folder, the need to be copied to the klipper folder with the name `.config`.
> 
> EDIT: What program are you using for SSH?

Putty. I ended up getting it flashed using the menuconfig from https://github.com/leadustin/QIDI-up2date-english. Using rp2040, 16k bootloader, usbserial communication, Flashing was successful but upon reinstalling the toolhead board to the qidi wiring the host no longer boots. If i unplug the toolhead the host will boot. I rechecked my soldering several times to make sure i didn't have two terminals bridge or something. So either i somehow broke the toolhead board or the menuconfig i used is wrong.

**Comment by frap129** [comment]
> > > cp: cannot stat '/home/mks/openq1/mcu_configs/.config.mainboard': No such file or directory
> > 
> > 
> > Where is this error from?
> > > Also I cant figure out how to add the files to the klipper/config folder properly. I add them but they dont seem to have any effect on the menuconfig. Trying to decipher the file and select the correct settings manually. Can you just provide a screenshot of the menuconfig settings?
> > 
> > 
> > You're missing the `.` in front of config. They do not go in the config folder, the need to be copied to the klipper folder with the name `.config`.
> > EDIT: What program are you using for SSH?
> 
> Putty. I ended up getting it flashed using the menuconfig from https://github.com/leadustin/QIDI-up2date-english. Using rp2040, 16k bootloader, usbserial communication, Flashing was successful but upon reinstalling the toolhead board to the qidi wiring the host no longer boots. If i unplug the toolhead the host will boot. I rechecked my soldering several times to make sure i didn't have two terminals bridge or something. So either i somehow broke the toolhead board or the menuconfig i used is wrong.

@Peck07 reported this in the discord earlier today, it doesn't seem to be related to the config. I will be doing a full reinstall on my own printer to investigate this later today.

**Comment by 53Aries** [comment]
> > > > cp: cannot stat '/home/mks/openq1/mcu_configs/.config.mainboard': No such file or directory
> > > 
> > > 
> > > Where is this error from?
> > > > Also I cant figure out how to add the files to the klipper/config folder properly. I add them but they dont seem to have any effect on the menuconfig. Trying to decipher the file and select the correct settings manually. Can you just provide a screenshot of the menuconfig settings?
> > > 
> > > 
> > > You're missing the `.` in front of config. They do not go in the config folder, the need to be copied to the klipper folder with the name `.config`.
> > > EDIT: What program are you using for SSH?
> > 
> > 
> > Putty. I ended up getting it flashed using the menuconfig from https://github.com/leadustin/QIDI-up2date-english. Using rp2040, 16k bootloader, usbserial communication, Flashing was successful but upon reinstalling the toolhead board to the qidi wiring the host no longer boots. If i unplug the toolhead the host will boot. I rechecked my soldering several times to make sure i didn't have two terminals bridge or something. So either i somehow broke the toolhead board or the menuconfig i used is wrong.
> 
> @Peck07 reported this in the discord earlier today, it doesn't seem to be related to the config. I will be doing a full reinstall on my own printer to investigate this later today.

What discord server? Thanks

**Comment by frap129** [comment]
@53Aries [the unofficial QIDI discord](https://discord.com/invite/bzPZmkmr). We have a thread going for custom firmware work in the q-series-forum channel

**Comment by frap129** [comment]
Update: This ended up being a klipper/katapult configuration error. Fixed in recent commits.
