### ISSUE TITLE
Orca Slicer

### ISSUE THREAD

**Issue by Pukkahq** [frap129/OpenQ1#6]
I found this project the other day and have ordered an EMMC card so I can flash my Q1 Pro.

Do I need to change any start or end macros in orca slice to OpenQ1?

If I want to revert back to the stock firmware is this a straight forward process?

**Comment by frap129** [comment]
You do not need to change your start/end macros in OrcaSlicer. In the layer change gcode in OrcaSlicer, it calls "LOG_Z", a macro that does not exist in OpenQ1. You do not need to remove this, but your klipper console will show "Unknown command LOG_Z".

Reverting back is easy, all that needs to be done is building/flashing klipper for the MCU's using the stock EMMC card. I do plan on writing a "Getting back to stock" guide at some point, though the process is almost the same as installing OpenQ1

**Comment by Pukkahq** [comment]
Thanks for the quick reply 😄 

Just waiting for the postman to arrive now!

**Comment by vonwerderc** [comment]
> Thanks for the quick reply 😄
> 
> Just waiting for the postman to arrive now!

Did you get this installed? Curious how easy it is to get up and running. I'm not incredibly confident in my soldering ability.
