### ISSUE TITLE
Loading Image to EMMC

### ISSUE THREAD

**Issue by Pukkahq** [frap129/OpenQ1#7]
Today I have received a new EMMC card but it looks like the adaptor is faulty as I cannot get it to read on multiple computers and card adaptors. I even tried the working one from the printer. 

Do you know anyway is it possible to upload the image via a SD card on the controller or can I plug the controller into a computer via usb and upload the image?

I know its a long shot but will be another week before a replacement card/adaptor arrives :(

**Comment by frap129** [comment]
Nope, the onboard SD card slot is for the primary MCU (not the host that runs linux) and there is no way to upload via USB on the host. EMMC adapter is required.
